*Importando o Pandas*

In [1]:
import pandas as pd

#definindo quantidade de linhas e colunas visiveis
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

*Importação de arquivos EXCEL*

In [3]:
hospital = 'Vila Nova Star Mar'
caminho = ('G:/Drives compartilhados/Qualidade/ACURÁCIA/DISCREPÂNCIA/DISCREPÂNCIA DIAGNÓSTICA/Discrepância 2026/Mar/')
df = pd.read_excel(caminho + 'Discrepancia ' + hospital + ' 2026.xlsx')
df_bck = df.copy()

In [4]:
df['Ds setor atendimento'].value_counts()

Ds setor atendimento
VNS2 - Centro Cirúrgico             916
VNS1 - Centro Cirúrgico             177
VNS2 - Hemodinâmica                  48
VNS1 - Hemodinâmica                  22
VNS1 - UTI 11º Andar                  1
SADT EDA - CCVNS                      1
Pronto Socorro Adulto (HMB)           1
VNS2 - Arsenal Centro Cirúrgico       1
Name: count, dtype: int64

*Criando o dataframe de CIDs.*

In [5]:
df.loc[df['Validacao cid'] == "CID DIFERENTE", 'Cor'] = ""

In [6]:
df

,þÿNr atendimento,Nr cirurgia,Nome paciente,Ds setor atendimento,Dt inicio cirurgia,Ds procedimento,Nom usuario registro,Nome,Dt registro,Diagnostico pre,Diagnostico pós,Validacao cid,Cor
0,52128572,1888289,Filipe Carvalho de Alencar,VNS1 - Centro Cirúrgico,2026-02-28 11:30:00,"Laparotomia Exploradora, Ou Para Biópsia, Ou P...",alexandre.coelh,Alexandre Coelho Guimaraes,2026-03-01 00:09:00,DOR ABDOMINAL E PELVICA,NEOPLASIA MALIGNA DO COLON,CID DIFERENTE,
1,52858754,1889119,Vania Aranha Zito,VNS2 - Centro Cirúrgico,2026-03-01 03:10:00,Fraturas E/Ou Luxações Ao Nível Do Tornozelo -...,sandro.zelada,Sandro Ricardo Benites Zelada,2026-03-01 04:00:00,FRATURA DA PERNA INCLUINDO TORNOZELO,FRATURA DO MALEOLO LATERAL,CID DIFERENTE,
2,52844113,1889027,Fernando Rocca da Cunha,VNS2 - Centro Cirúrgico,2026-03-01 06:25:00,Drenagem De Abscesso Cervical Profundo,agaillard,Alfredo Lara Gaillard,2026-03-01 07:14:00,ABSCESSO PERIAMIGDALIANO_x000D_CELULITE DA FACE,DOENCAS DAS VIAS AEREAS SUPERIORES,CID DIFERENTE,
3,52859355,1888595,Debora Yuri Moura Nakamura,VNS2 - Centro Cirúrgico,2026-03-01 07:20:00,Retirada De Corpo Estranho Da Parede Torácica,felipe.zampieri,Felipe Muniz de Castro Zampieri,2026-03-01 11:58:00,COMPLICACAO MECANICA DE PROTESE E IMPLANTE MAM...,COMPLICACAO MECANICA DE PROTESE E IMPLANTE MAM...,CID IGUAL,NaN
4,52808250,1889030,Rogerio Teixeira Rosolen,VNS2 - Centro Cirúrgico,2026-03-01 10:20:00,Septoplastia (Qualquer Técnica),daniela.costam,Daniela Costa Malheiros,2026-03-01 12:06:00,SINUSITE CRONICA,OUTRAS SINUSITES CRONICAS,CID DIFERENTE,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1162,53529597,1912446,Rafael Siqueira Martins,VNS2 - Centro Cirúrgico,2026-03-30 15:10:00,Rinosseptoplastia Funcional,roney.gfeitosa,Roney Goncalves Fechine Feitosa,2026-03-30 21:59:00,DESVIO DO SEPTO NASAL,DESVIO DO SEPTO NASAL,CID IGUAL,NaN
1163,53510018,1913633,Christine Mendonca,VNS2 - Centro Cirúrgico,2026-03-30 18:35:00,Enterectomia Segmentar,diego.vaz,Diego Greatti Vaz da Silva,2026-03-30 22:02:00,DOR ABDOMINAL E PELVICA,ABDOME AGUDO,CID DIFERENTE,
1164,53520576,1913614,Andre Luis Benevides de Oliveira,VNS1 - Centro Cirúrgico,2026-03-30 20:54:00,Fraturas E/Ou Luxações E/Ou Avulsões - Tratame...,ricardo.barriel,Ricardo Berriel Mendes,2026-03-30 22:22:00,TRAUMATISMO DE REGIAO NAO ESPECIFICADA DO CORPO,LUXACAO DA ARTICULACAO ACROMIOCLAVICULAR,CID DIFERENTE,
1165,53514959,1913613,Cilene Oliveira da Silva,VNS2 - Centro Cirúrgico,2026-03-30 21:25:00,Colecistectomia Com Colangiografia Por Videola...,jreina,Jorge Henrique Reina,2026-03-30 22:53:00,DOR ABDOMINAL E PELVICA,CISTITE,CID DIFERENTE,
1166,53377709,1912530,Thiago Marini Murca,VNS2 - Centro Cirúrgico,2026-03-30 21:50:00,Nefrolitotomia Percutânea Unilateral,rafael.astolfi,Rafael Haddad Astolfi,2026-03-30 23:54:00,OUTROS TRANSTORNOS POS-PROCEDIMENTOS DO APAREL...,NaN,CID DIFERENTE,

*Obtendo nomes das colunas*

In [7]:
df.columns

Index(['þÿNr atendimento', 'Nr cirurgia', 'Nome paciente',
       'Ds setor atendimento', 'Dt inicio cirurgia', 'Ds procedimento',
       'Nom usuario registro', 'Nome', 'Dt registro', 'Diagnostico pre',
       'Diagnostico pós', 'Validacao cid', 'Cor'],
      dtype='str')

*Remover linhas que não contem resposta*

In [8]:
# O raciocínio: Localize as linhas onde isnull() é True e mude a coluna 'Cor'
df.loc[df['Diagnostico pós'].isnull(), 'Cor'] = "Amarelo"
print(df.loc[df['Diagnostico pós'].isnull()])

      þÿNr atendimento  Nr cirurgia                      Nome paciente  \
77            52843453      1889759         Alessandro Landskron Diniz
104           52768846      1890951              Daniela Citraro Marra
302           53016429      1893869  Marina Lopes do Nascimento Lovato
784           53299926      1904249                        Nives Zoppe
1158          53523173      1912441         Francini Cristelo de Souza
1166          53377709      1912530                Thiago Marini Murca

         Ds setor atendimento   Dt inicio cirurgia  \
77       VNS2 - Hemodinâmica   2026-03-02 12:53:00
104   VNS2 - Centro Cirúrgico  2026-03-03 13:20:00
302   VNS2 - Centro Cirúrgico  2026-03-08 07:35:00
784   VNS2 - Centro Cirúrgico  2026-03-20 13:45:00
1158  VNS2 - Centro Cirúrgico  2026-03-30 12:40:00
1166  VNS2 - Centro Cirúrgico  2026-03-30 21:50:00

                                        Ds procedimento Nom usuario registro  \
77    Angioplastia Transluminal Percutânea Por Balão...              rstaico
104   Laparotomia Exploradora, Ou Para Biópsia, Ou P...       luciana.michel
302   Endometriose Peritoneal - Tratamento Cirúrgico...       guilherme.gava
784          Câncer De Ovário (Debulking) Laparoscópica        andre.lfarias
1158  Diástase Dos Retos-Abdominais - Tratamento Cir...           ehentschel
1166               Nefrolitotomia Percutânea Unilateral       rafael.astolfi

                                          Nome         Dt registro  \
77                              Rodolfo Staico 2026-03-03 09:22:00
104   Luciana Cristina Pereira Ferreira Michel 2026-03-03 16:02:00
302                      Guilherme Mendes Gava 2026-03-08 14:24:00
784              Andre Lopes de Farias E Silva 2026-03-20 21:01:00
1158                   Eduardo Lange Hentschel 2026-03-30 21:03:00
1166                     Rafael Haddad Astolfi 2026-03-30 23:54:00

                                        Diagnostico pre Diagnostico pós  \
77    DOENCAS ISQUEMICAS AGUDAS DO CORACAO_x000D_DOE...             NaN
104                     ENDOMETRIOSE_x000D_ENDOMETRIOSE             NaN
302               Endometriose_x000D_Leiomioma do utero             NaN
784   Neoplasia maligna do ovario_x000D_Neoplasia ma...             NaN
1158  DIASTASE DE MUSCULO_x000D_TRANSTORNO DA MAMA N...             NaN
1166  OUTROS TRANSTORNOS POS-PROCEDIMENTOS DO APAREL...             NaN

      Validacao cid      Cor
77    CID DIFERENTE  Amarelo
104   CID DIFERENTE  Amarelo
302   CID DIFERENTE  Amarelo
784   CID DIFERENTE  Amarelo
1158  CID DIFERENTE  Amarelo
1166  CID DIFERENTE  Amarelo

*Classificação de Dados*

In [9]:
df.sort_values(by=["Nome paciente"])

,þÿNr atendimento,Nr cirurgia,Nome paciente,Ds setor atendimento,Dt inicio cirurgia,Ds procedimento,Nom usuario registro,Nome,Dt registro,Diagnostico pre,Diagnostico pós,Validacao cid,Cor
43,52878275,1889212,Adelita Batista Breda Guirau,VNS2 - Centro Cirúrgico,2026-03-02 13:50:00,Colecistectomia Com Colangiografia Por Videola...,rjesus,Roodney Forster de Jesus,2026-03-02 15:37:00,COLELITIASE,COLELITIASE_x000D_OUTROS CISTOS OVARIANOS E OS...,CID DIFERENTE,
907,53362499,1908458,Ademir Jose Rodrigues,VNS2 - Centro Cirúrgico,2026-03-24 15:35:00,"Incisão E Drenagem De Abscesso, Hematoma Ou Pa...",joao.siufi,Joao Siufi Neto,2026-03-24 16:06:00,L02 Abscesso cutaneo furunculo e carbunculo,L02 Abscesso cutaneo furunculo e carbunculo,CID IGUAL,NaN
675,53255955,1902465,Adolfo Chaves Marcondes de Souza,VNS2 - Centro Cirúrgico,2026-03-18 14:15:00,Coluna Vertebral: Infiltração Foraminal Ou Fac...,marcelo.goiri,Marcelo Augusto Acosta Goiri,2026-03-18 14:53:00,M54.5 Dor lombar baixa,M54.5 Dor lombar baixa,CID IGUAL,NaN
1142,53514023,1912085,Adriana Aquila Silva Caversan Roos,VNS2 - Centro Cirúrgico,2026-03-30 06:30:00,Ritidoplastia / Lifiting,felipe.cgomes,Felipe Amado Cerqueira Gomes,2026-03-30 12:57:00,OUTRO SEGUIMENTO CIRURGICO,OUTRO SEGUIMENTO CIRURGICO,CID IGUAL,NaN
1098,53491856,1911083,Adriana Chaves Borges Hautekeur,VNS2 - Centro Cirúrgico,2026-03-28 06:55:00,Dermatocalaze Ou Blefarocalaze - Unilateral,rodrigo.arruda,Rodrigo Garcia de Arruda,2026-03-28 13:39:00,PTOSE DA PALPEBRA,PTOSE DA PALPEBRA,CID IGUAL,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,52923081,1891358,Yumi Melo Yamada,VNS2 - Centro Cirúrgico,2026-03-04 06:30:00,Mastoplastia Redutora/Mamoplastia/Mastopexia c...,ricardo.proto,Ricardo Sestito Proto,2026-03-04 10:21:00,OUTROS TRANSTORNOS ESPECIFICADOS DA MAMA,OUTROS TRANSTORNOS ESPECIFICADOS DA MAMA,CID IGUAL,NaN
1062,53480913,1898765,Zebedeu Fernandes de Souza,VNS2 - Centro Cirúrgico,2026-03-27 15:30:00,Osteoplastia Ou Discectomia Percutânea (Verteb...,alberto.jacob,Alberto Emanuel Gerbi Jacob,2026-03-27 16:16:00,TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...,TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...,CID IGUAL,NaN
933,53408803,1908972,Zenildo Ressurreicao Fonseca,Pronto Socorro Adulto (HMB),,Denervação Percutânea De Faceta Articular - Po...,lara.santos,Lara Guercio dos Santos,2026-03-25 07:40:00,M54.3 Ciatica,M54.3 Ciatica,CID IGUAL,NaN
1149,53514221,1912063,Zilda Maria Alves Matheus,VNS2 - Centro Cirúrgico,2026-03-30 06:35:00,Ritidoplastia / Lifiting,carlucio.rogogn,Carlucio Martins Ragognete,2026-03-30 16:07:00,SEGUIMENTO ENVOLVENDO CIRURGIA PLASTICA DA CAB...,SEGUIMENTO ENVOLVENDO CIRURGIA PLASTICA DA CAB...,CID IGUAL,NaN
918,53389985,1908479,Zirlene Soares Pereira,VNS2 - Centro Cirúrgico,2026-03-24 18:55:00,Etmoidectomia Intranasal Por Videoendoscopia,deusdedit.neto,Deusdedit Brandao Neto,2026-03-24 19:21:00,J01 Sinusite aguda,J01 Sinusite aguda,CID IGUAL,NaN

*Filtrando os dados*

In [10]:
# Filtrando linhas coma palavra Convalescenca
conva = df['Diagnostico pós'].str.contains('CONVALESCENCA', na=False,case=False)
df.loc[conva, 'Cor'] = "Amarelo"
# Exibindo as linhas corretas
print(df[df['Diagnostico pós'].str.contains('CONVALESCENCA', na=False,case=False)])

      þÿNr atendimento  Nr cirurgia  \
12            52866328      1889263
214           52977316      1893134
242           52988539      1892645
251           52995606      1886430
406           53077971      1896610
474           52922317      1890742
646           53228407      1902838
650           53242340      1902293
840           53348657      1906749
852           53352948      1906759
1046          53467868      1910226
1056          53470482      1910287

                                       Nome paciente     Ds setor atendimento  \
12                            Matteo Caldart Jahshan  VNS1 - Centro Cirúrgico
214                        Pedro Afonso Lutz Barbosa  VNS1 - Centro Cirúrgico
242                 Serena Francesca Salvade Carmona  VNS2 - Centro Cirúrgico
251                           Marcelo de Caro Santos  VNS2 - Centro Cirúrgico
406                      Luzia Eliana Reis Magalhaes  VNS2 - Centro Cirúrgico
474                               Eder Campos Behnck  VNS2 - Centro Cirúrgico
646                                  Suelen Vizzotto  VNS2 - Centro Cirúrgico
650                 Thaiz Angelica Franzoni da Silva  VNS2 - Centro Cirúrgico
840                           Mariana Parolin Lozano  VNS1 - Centro Cirúrgico
852              Stephanie Goncalves Pedroso Ribeiro  VNS1 - Centro Cirúrgico
1046                    Rosana Claudia Scramin Wakim  VNS2 - Centro Cirúrgico
1056  Ligia Cristina Vassallo Leme Barbosa Vernaglia  VNS2 - Centro Cirúrgico

       Dt inicio cirurgia                                    Ds procedimento  \
12    2026-03-02 05:40:00                               Adeno-Amigdalectomia
214   2026-03-06 06:30:00                                      Blefarorrafia
242   2026-03-06 13:30:00                 Histerectomia Total (Qualquer Via)
251   2026-03-06 16:55:00                              Pênis Curvo Congênito
406   2026-03-10 21:25:00  Incisão E Drenagem De Abscesso, Hematoma Ou Pa...
474   2026-03-04 12:30:00  Diástase Dos Retos-Abdominais - Tratamento Cir...
646   2026-03-17 19:20:00                      Gravidez  Ectópica - Cirurgia
650   2026-03-18 07:30:00  Colecistectomia Com Colangiografia Por Videola...
840   2026-03-23 07:40:00                  Histerectomia Total Laparoscópica
852   2026-03-23 11:40:00  Endometriose Peritoneal - Tratamento Cirúrgico...
1046  2026-03-27 11:30:00  Histeroscopia Com Ressectoscópio Para Miomecto...
1056  2026-03-27 12:50:00  Histeroscopia Cirúrgica P/ Biópsia Dirigida, L...

     Nom usuario registro                              Nome  \
12         vinicius.palma          Vinicius de Moraes Palma
214        tiago.oliveira           Tiago Ortiz de Oliveira
242              mgabriel              Mirna Gabriel Nakano
251         vitor.sjunior  Vitor Lazarini dos Santos Junior
406       raquel.rmagalha             Raquel Reis Magalhaes
474        nauana.beraldo  Nauana Cristine Beraldo Lourenco
646       debora.fernande      Debora Amorim Oria Fernandes
650        nauana.beraldo  Nauana Cristine Beraldo Lourenco
840          ana.lauletta      Ana Luisa Fernandes Lauletta
852          ana.lauletta      Ana Luisa Fernandes Lauletta
1046        marta.nakamae               Marta Naomi Nakamae
1056        marta.nakamae               Marta Naomi Nakamae

             Dt registro                                    Diagnostico pre  \
12   2026-03-02 05:19:00                                     APNEIA DE SONO
214  2026-03-06 08:18:00                               H02.3 Blefarocalasia
242  2026-03-06 15:40:00  N93.9 Sangramento anormal do utero ou da vagin...
251  2026-03-06 17:55:00  Q55.6 Outr malformacoes congen do penis       ...
406  2026-03-10 22:45:00  L02.9 Abscesso cutaneo furunculo carbunculo lo...
474  2026-03-12 13:07:00                               K43   Hernia ventral
646  2026-03-17 20:56:00                                  Gravidez ectopica
650  2026-03-18 07:20:00                                  K80   Colelitiase
840  2026-03-23 10:23:00  N93.9 Sangramento anormal do utero ou da vagin...
852  2026-03-23 14:10:00                                       Endometriose
1046 2026-03-27 12:22:00  POLIPO DO TRATO GENITAL FEMININO NAO ESPECIFICADO
1056 2026-03-27 13:36:00                        CONVALESCENCA APOS CIRURGIA

                                       Diagnostico pós  Validacao cid      Cor
12    APNEIA DE SONO_x000D_CONVALESCENCA APOS CIRURGIA  CID DIFERENTE  Amarelo
214                  Z54.0 Convalescenca apos cirurgia  CID DIFERENTE  Amarelo
242                  Z54.0 Convalescenca apos cirurgia  CID DIFERENTE  Amarelo
251                  Z54.0 Convalescenca apos cirurgia  CID DIFERENTE  Amarelo
406                  Z54.0 Convalescenca apos cirurgia  CID DIFERENTE  Amarelo
474                  Z54.0 Convalescenca apos cirurgia  CID DIFERENTE  Amarelo
646                  Z54.0 Convalescenca apos cirurgia  CID DIFERENTE  Amarelo
650                  Z54.0 Convalescenca apos cirurgia  CID DIFERENTE  Amarelo
840                                Z54   Convalescenca  CID DIFERENTE  Amarelo
852                                Z54   Convalescenca  CID DIFERENTE  Amarelo
1046                       CONVALESCENCA APOS CIRURGIA  CID DIFERENTE  Amarelo
1056                       CONVALESCENCA APOS CIRURGIA      CID IGUAL  Amarelo

In [11]:
outros = df['Diagnostico pós'].str.contains('OUTROS', na=False, case=False)
df.loc[outros, 'Cor'] = "Amarelo"

print(df[df['Diagnostico pós'].str.contains('OUTROS', na=False, case=False)])

      þÿNr atendimento  Nr cirurgia                     Nome paciente  \
7             52854767      1889029               Luca Coutinho Melao
15            52865474      1888723          Maria Borgneth Maringoni
19            52866134      1889350         Ana Flora Vaz Lobato Diaz
21            52866322      1889229     Tanise Sirotsky Dvoskin Dutra
43            52878275      1889212      Adelita Batista Breda Guirau
58            52890779      1849665          Renata Uhlmann Domingues
61            52865095      1890095           Nicoly Almeida de Sousa
69            52896389      1889500  Viviane Ferreira Augusto Lacerda
81            52896292      1890371             Taciana Mari Tsutsumi
102           52885178      1890422              Lineu Jose Goncalves
133           52923249      1890736        Solange Medeiros Tiltscher
136           52923081      1891358                  Yumi Melo Yamada
158           52927263      1892168         Valdinei Pereira da Silva
170           52952414      1891590             Andressa Garcia Diniz
1044          53466843      1910219             Gregory Sartorato Vaz
1062          53480913      1898765        Zebedeu Fernandes de Souza
1066          53471470      1910512   Richard de Albanesi Professiori
1084          53489846      1868524                     Mendel Sanger
1103          53502836      1912397         Natasha Abreu de Oliveira
1116          53494897      1912733        Luis Andre Lemos de Moraes
1125          53513764      1912130   Gilson Jose Carneiro Leao Filho
1131          53298332      1913180                     Rosa de Sales
1146          53527935      1913478           Renata Loubet Guimaraes

         Ds setor atendimento   Dt inicio cirurgia  \
7     VNS2 - Centro Cirúrgico  2026-03-01 10:45:00
15    VNS2 - Centro Cirúrgico  2026-03-02 06:55:00
19    VNS2 - Centro Cirúrgico  2026-03-02 08:24:00
21    VNS1 - Centro Cirúrgico  2026-03-02 06:20:00
43    VNS2 - Centro Cirúrgico  2026-03-02 13:50:00
58    VNS2 - Centro Cirúrgico  2026-03-02 20:40:00
61    VNS2 - Centro Cirúrgico  2026-03-02 21:00:00
69    VNS2 - Centro Cirúrgico  2026-03-03 06:40:00
81    VNS2 - Centro Cirúrgico  2026-03-03 07:36:00
102   VNS2 - Centro Cirúrgico  2026-03-03 12:20:00
133   VNS2 - Centro Cirúrgico  2026-03-04 07:20:00
136   VNS2 - Centro Cirúrgico  2026-03-04 06:30:00
158   VNS2 - Centro Cirúrgico  2026-03-04 20:15:00
170   VNS2 - Centro Cirúrgico  2026-03-05 07:25:00
1044  VNS2 - Centro Cirúrgico  2026-03-27 10:00:00
1062  VNS2 - Centro Cirúrgico  2026-03-27 15:30:00
1066  VNS1 - Centro Cirúrgico  2026-03-27 13:30:00
1084  VNS2 - Centro Cirúrgico  2026-03-28 07:39:00
1103  VNS2 - Centro Cirúrgico  2026-03-28 22:40:00
1116  VNS2 - Centro Cirúrgico  2026-03-29 22:15:00
1125  VNS2 - Centro Cirúrgico  2026-03-30 07:10:00
1131     VNS2 - Hemodinâmica   2026-03-30 09:20:00
1146  VNS2 - Centro Cirúrgico  2026-03-30 13:59:00

                                        Ds procedimento Nom usuario registro  \
7     Fraturas E/Ou Luxações E/Ou Avulsões - Tratame...          lucas.nigro
15    Transposição De Mais De 1 Tendão - Tratamento ...          bruno.zanon
19    RECONSTRUÇÃO, RETENCIONAMENTO OU REFORÇO DO LI...          bruno.zanon
21                            Ritidoplastia / Lifiting          lucio.Issamu
43    Colecistectomia Com Colangiografia Por Videola...               rjesus
58    Toalete Cirúrgica - Correção De Joelho Flexo -...      leonardo.ataide
61          Luxação do Tornozelo - Tratamento Cirúrgico          lucas.nigro
69                          Rinosseptoplastia Funcional       fabiola.nagoya
81    Sinusectomia Maxilar - Via Endonasal Por Video...       caio.gfloriano
102   Tratamento Microcirúrgico Do Canal Vertebral E...            l.rsantos
133                                Microneurólise Única      marcio.ffreitas
136   Mastoplastia Redutora/Mamoplastia/Mastopexia c...        ricardo.proto
158   Coluna Vertebral: Infiltração Foraminal Ou Fac...      raphael.gregnan
170                                Tireoidectomia Total           davi.knoll
1044  RECONSTRUÇÃO, RETENCIONAMENTO OU REFORÇO DO LI...          bruno.zanon
1062  Osteoplastia Ou Discectomia Percutânea (Verteb...        alberto.jacob
1066             Cirurgia De Coluna Por Via Endoscópica      ricardo.gracian
1084             Cirurgia De Coluna Por Via Endoscópica       ulisses.aguiar
1103  Extensos Ferimentos, Cicatrizes Ou Tumores - E...                bknop
1116  Biópsia Endoscópica De Bexiga (Inclui Cistosco...         daniel.moser
1125                 Paratireoidectomia Com Toracotomia      barbara.greggio
1131  Denervação Percutânea De Faceta Articular - Po...      alexandre.kochi
1146                    Lesão Anal - Eletrocauterização               jreina

                                     Nome         Dt registro  \
7                             Lucas Nigro 2026-03-01 13:16:00
15                   Bruno Bonganha Zanon 2026-03-02 07:25:00
19                   Bruno Bonganha Zanon 2026-03-02 08:54:00
21                  Lucio Issamu Nakayama 2026-03-02 09:39:00
43               Roodney Forster de Jesus 2026-03-02 15:37:00
58        Leonardo Soares Ataide Oliveira 2026-03-02 20:39:00
61                            Lucas Nigro 2026-03-02 22:20:00
69      Fabiola Rodrigues Oliveira Nagoya 2026-03-03 08:08:00
81                    Caio Gomes Floriano 2026-03-03 09:57:00
102   Lucas de Souza Rodrigues dos Santos 2026-03-03 15:32:00
133               Marcio de Faria Freitas 2026-03-04 09:14:00
136                 Ricardo Sestito Proto 2026-03-04 10:21:00
158          Raphael Casarotto Gregnanini 2026-03-04 21:44:00
170                    Davi Knoll Ribeiro 2026-03-05 10:50:00
1044                 Bruno Bonganha Zanon 2026-03-27 11:44:00
1062          Alberto Emanuel Gerbi Jacob 2026-03-27 16:16:00
1066           Ricardo Squiapati Graciano 2026-03-27 17:48:00
1084              Ulisses do Prado Aguiar 2026-03-28 09:09:00
1103               Breno Albuquerque Knop 2026-03-29 01:12:00
1116  Daniel Carlos Uliano Moser da Silva 2026-03-29 22:55:00
1125                      Barbara Greggio 2026-03-30 09:38:00
1131         Alexandre Israel Kochi Silva 2026-03-30 11:03:00
1146                 Jorge Henrique Reina 2026-03-30 14:56:00

                                        Diagnostico pre  \
7       TRAUMATISMO DE REGIAO NAO ESPECIFICADA DO CORPO
15                OUTROS TRANSTORNOS INTERNOS DO JOELHO
19                OUTROS TRANSTORNOS INTERNOS DO JOELHO
21    OUTRAS ALTERACOES CUTANEAS_x000D_OUTROS TRANST...
43                                          COLELITIASE
58                OUTROS TRANSTORNOS INTERNOS DO JOELHO
61                     ENTORSE E DISTENSAO DO TORNOZELO
69       OUTROS TRANSTORNOS ESPECIFICADOS DAS PALPEBRAS
81                                       APNEIA DE SONO
102                                    DOR LOMBAR BAIXA
133                     OUTROS CISTOS DE BOLSA SINOVIAL
136            OUTROS TRANSTORNOS ESPECIFICADOS DA MAMA
158                                    DOR LOMBAR BAIXA
170              NEOPLASIA MALIGNA DA GLANDULA TIREOIDE
1044              OUTROS TRANSTORNOS INTERNOS DO JOELHO
1062  TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...
1066  TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...
1084  DOR LOMBAR BAIXA_x000D_TRANSTORNOS DE DISCOS L...
1103                                          DOR AGUDA
1116  DOR ABDOMINAL E PELVICA_x000D_OUTROS ACHADOS A...
1125  HIPERPARATIREOIDISMO E OUTROS TRANSTORNOS DA G...
1131  INFECCAO DO TRATO URINARIO DE LOCALIZACAO NAO ...
1146  PAPILOMAVIRUS, COMO CAUSA DE DOENCAS CLASSIFIC...

                                        Diagnostico pós  Validacao cid  \
7           OUTROS ESTADOS POS-CIRURGICOS ESPECIFICADOS  CID DIFERENTE
15                OUTROS TRANSTORNOS INTERNOS DO JOELHO      CID IGUAL
19    OUTROS TRANSTORNOS INTERNOS DO JOELHO_x000D_OU...  CID DIFERENTE
21    OUTRAS ALTERACOES CUTANEAS_x000D_OUTROS TRANST...      CID IGUAL
43    COLELITIASE_x000D_OUTROS CISTOS OVARIANOS E OS...  CID DIFERENTE
58                OUTROS TRANSTORNOS INTERNOS DO JOELHO      CID IGUAL
61          OUTROS ESTADOS POS-CIRURGICOS ESPECIFICADOS  CID DIFERENTE
69       OUTROS TRANSTORNOS ESPECIFICADOS DAS PALPEBRAS      CID IGUAL
81    APNEIA DE SONO_x000D_OUTROS ESTADOS POS-CIRURG...  CID DIFERENTE
102   TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...  CID DIFERENTE
133                     OUTROS CISTOS DE BOLSA SINOVIAL      CID IGUAL
136            OUTROS TRANSTORNOS ESPECIFICADOS DA MAMA      CID IGUAL
158   TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...  CID DIFERENTE
170         OUTROS ESTADOS POS-CIRURGICOS ESPECIFICADOS  CID DIFERENTE
1044              OUTROS TRANSTORNOS INTERNOS DO JOELHO      CID IGUAL
1062  TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...      CID IGUAL
1066  TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...      CID IGUAL
1084  DOR LOMBAR BAIXA_x000D_TRANSTORNOS DE DISCOS L...      CID IGUAL
1103           OUTROS TRANSTORNOS ESPECIFICADOS DA MAMA  CID DIFERENTE
1116                   OUTROS ACHADOS ANORMAIS NA URINA  CID DIFERENTE
1125  HIPERPARATIREOIDISMO E OUTROS TRANSTORNOS DA G...      CID IGUAL
1131  TRANSTORNOS DE DISCOS LOMBARES E DE OUTROS DIS...  CID DIFERENTE
1146  PAPILOMAVIRUS, COMO CAUSA DE DOENCAS CLASSIFIC...      CID IGUAL

          Cor
7     Amarelo
15    Amarelo
19    Amarelo
21    Amarelo
43    Amarelo
58    Amarelo
61    Amarelo
69    Amarelo
81    Amarelo
102   Amarelo
133   Amarelo
136   Amarelo
158   Amarelo
170   Amarelo
1044  Amarelo
1062  Amarelo
1066  Amarelo
1084  Amarelo
1103  Amarelo
1116  Amarelo
1125  Amarelo
1131  Amarelo
1146  Amarelo

In [12]:
segui = df['Diagnostico pós'].str.contains('Seguimentos', na=False, case=False)
df.loc[segui, 'Cor'] = "Amarelo"

print(df[df['Diagnostico pós'].str.contains('Seguimentos', na=False, case=False)])

Empty DataFrame
Columns: [þÿNr atendimento, Nr cirurgia, Nome paciente, Ds setor atendimento, Dt inicio cirurgia, Ds procedimento, Nom usuario registro, Nome, Dt registro, Diagnostico pre, Diagnostico pós, Validacao cid, Cor]
Index: []

In [13]:
df.loc[df['Validacao cid']== "CID IGUAL", 'Cor'] = 'Verde'

*Removendo caracteres indesejados*

In [14]:
count = 0
for linha in df.index:
    if df.loc[linha, 'Diagnostico pre'].count('_x000D_') >= 2:
        print(linha, df.loc[linha, 'Diagnostico pre'])
        count += 1
        
print(count)

21 OUTRAS ALTERACOES CUTANEAS_x000D_OUTROS TRANSTORNOS ESPECIFICADOS DO NARIZ E DOS SEIOS PARANASAIS_x000D_HIPERTROFIA DA VULVA
33 OUTRAS MALFORMACOES CONGENITAS DOS ORGAOS GENITAIS MASCULINOS_x000D_HIPERTROFIA DO PREPUCIO, FIMOSE E PARAFIMOSE_x000D_ESTENOSE DA URETRA
64 PARALISIA DE BELL_x000D_EPISODIO DEPRESSIVO MODERADO_x000D_NEOPLASIA DE COMPORTAMENTO INCERTO OU DESCONHECIDO DO ENCEFALO, NAO ESPECIFICADO
96 NEOPLASIA DE COMPORTAMENTO INCERTO OU DESCONHECIDO DO MEDIASTINO_x000D_NEOPLASIA DE COMPORTAMENTO INCERTO OU DESCONHECIDO DO MEDIASTINO_x000D_LINFOMA DE CELULAS B, NAO ESPECIFICADO
176 Hipertrofia da vulva_x000D_N64   Outr doenc da mama_x000D_E65   Adiposidade localizada
251 Q55.6 Outr malformacoes congen do penis           _x000D_Hipertrofia do prepucio, fimose e parafimose_x000D_N35.9 Estenose uretral NE
321 R23   Outr alteracoes cutaneas_x000D_E88.1 Lipodistrofia NCOP                          _x000D_E65   Adiposidade localizada
361 K21   Doenc de refluxo gastroesofagico_x000D_K40   Hernia inguinal_x000D_K42   Hernia umbilical
382 T85.4 Complic mecanica protese implante mamarios  _x000D_L91   Afeccoes hipertroficas da pele_x000D_N90.6 Hipertrofia da vulva
388 K80   Colelitiase_x000D_K42   Hernia umbilical_x000D_M62   Outr transt musculares
403 L91.0 Cicatriz queloide                           _x000D_E88.1 Lipodistrofia NCOP                          _x000D_N60   Displasias mamarias benignas
446 J34.2 Desvio do septo nasal                       _x000D_J32   Sinusite cronica_x000D_J30   Rinite alergica e vasomotora
493 I82   Outr embolia e trombose venosas_x000D_D25.9 Leiomioma do utero NE                       _x000D_D25.9 Leiomioma do utero NE
576 M54.5 Dor lombar baixa                            _x000D_M75.8 Outr lesoes do ombro                        _x000D_M23.8 Outr transt internos do joelho
593 K80   Colelitiase_x000D_K42   Hernia umbilical_x000D_M62.0 Diastase de musculo                         _x000D_L91.0 Cicatriz queloide
599 K80   Colelitiase_x000D_K42.0 Hernia umbilical c/obstrucao s/gangrena     _x000D_K76.0 Degeneracao gordurosa do figado NCOP
605 R19.8 Outr sint sinais esp relat ap digest abdome _x000D_N62   Hipertrofia da mama_x000D_E88.1 Lipodistrofia NCOP
606 J34.2 Desvio do septo nasal                       _x000D_J32.4 Pansinusite cronica                         _x000D_J34.3 Hipertrofia dos cornetos nasais
629 R23   Outr alteracoes cutaneas_x000D_E88.1 Lipodistrofia NCOP                          _x000D_L91   Afeccoes hipertroficas da pele_x000D_L90.5 Cicatrizes e fibrose cutanea
631 K42   Hernia umbilical_x000D_K40   Hernia inguinal_x000D_K80   Colelitiase_x000D_M62.4 Contratura de musculo
683 M62.0 Diastase de musculo                         _x000D_E88.1 Lipodistrofia NCOP                          _x000D_N64.5 Outr sint e sinais da mama                  _x000D_K42   Hernia umbilical_x000D_E65   Adiposidade localizada
721 M62.0 Diastase de musculo                         _x000D_E88.1 Lipodistrofia NCOP                          _x000D_N64.5 Outr sint e sinais da mama
816 K07.0 Anomalias importantes tamanho da mandibula  _x000D_K07.2 Anomalias relacao entre as arcadas dentarias_x000D_K07.1 Anomalias relacao entre mandibula base cran _x000D_K07.5 Anormalidades dentofaciais funcionais       _x000D_K07.5 Anormalidades dentofaciais funcionais
839 I84   Hemorroidas_x000D_I84.6 Plicomas hemorroidarios residuais           _x000D_N90.6 Hipertrofia da vulva
890 J34.2 Desvio do septo nasal                       _x000D_J32   Sinusite cronica_x000D_J30   Rinite alergica e vasomotora
897 T85.4 Complic mecanica protese implante mamarios  _x000D_N90.6 Hipertrofia da vulva                        _x000D_N64.5 Outr sint e sinais da mama
911 M62.0 Diastase de musculo                         _x000D_L90.5 Cicatrizes e fibrose cutanea                _x000D_K42   Hernia umbilical_x000D_N63   Nodulo mamario NE
917 S72.9 Frat do femur parte NE                      _x000D_S72   Frat do femur_x000D_S62   Frat ao nivel do punho e da mao
944 Neoplasia maligna da mama_x000D_T85.4 Complic mecanica protese implante mamarios  _x000D_Y83.6 Remocao de um outr orgao                    _x000D_L91   Afeccoes hipertroficas da pele
983 I20   Angina pectoris_x000D_I20   Angina pectoris_x000D_I25   Doenc isquemica cronica do coracao
1011 M86.9 Osteomielite NE                             _x000D_T84.1 Complic mec disp fixacao int ossos membros  _x000D_T84.1 Complic mec disp fixacao int ossos membros
1047 HERNIA INGUINAL_x000D_HERNIA UMBILICAL_x000D_HIDROCELE E ESPERMATOCELE_x000D_TESTICULO NAO-DESCIDO, UNILATERAL
1071 FRATURA DA EXTREMIDADE PROXIMAL DA TIBIA_x000D_ENTORSE E DISTENSAO ENVOLVENDO LIGAMENTO CRUZADO (ANTERIOR) (POSTERIOR) DO JOELHO_x000D_ENTORSE E DISTENSAO ENVOLVENDO LIGAMENTO COLATERAL (PERONIAL) (TIBIAL) DO JOELHO
1148 DOR LOMBAR BAIXA_x000D_CERVICALGIA_x000D_SACROILEITE NAO CLASSIFICADA EM OUTRA PARTE_x000D_TENDINITE GLUTEA
34

In [15]:
len(df)

1167

In [16]:
linha = 17
texto = df.loc[linha, 'Diagnostico pre']
print(texto)
caracter_separador = texto.find('_x000D_')
print(caracter_separador)

AFECCOES ATROFICAS DA PELE
-1

In [17]:
print(len('_x000D_'))

7

In [ ]:
texto1 = texto[:caracter_separador]
print(texto1)
texto2 = texto[caracter_separador+len('_x000D_'):]
print(texto2)

In [ ]:
if (texto1 == texto2) == True:
    texto_principal = texto1
    print(texto_principal)
else:
    texto_principal = texto1 + ', ' + texto2
    print(texto_principal)

In [ ]:
df.loc[linha:linha]

In [ ]:
df.loc[linha, 'Diagnostico pós'] = texto_principal
df.loc[linha:linha]

*Retirando quebra linha da coluna 'Diagonostico Pré'*

In [ ]:
for linha in df.index:
    print('*'*100)
    print(linha)
    # -------------------------------------------
    texto = df.loc[linha, 'Diagnostico pre']
    print(texto)
    caracter_separador = texto.find('_x000D_')
    
    if caracter_separador == -1:
        continue
    
    print(caracter_separador)

    # -------------------------------------------
    print(len('_x000D_'))
    
    # -------------------------------------------
    texto1 = texto[:caracter_separador]
    print(texto1)
    texto2 = texto[caracter_separador+len('_x000D_'):]
    print(texto2)
    
    # -------------------------------------------
    if (texto1 == texto2) == True:
        texto_principal = texto1
        print(texto_principal)
    else:
        texto_principal = texto1 + ', ' + texto2
        print(texto_principal)
        
    # -------------------------------------------
    df.loc[linha, 'Diagnostico pre'] = texto_principal

*Replicando para remover*

In [ ]:
for linha in df.index:
    print('*'*100)
    print(linha)
    # -------------------------------------------
    texto = df.loc[linha, 'Diagnostico pre']
    print(texto)
    caracter_separador = texto.find('_x000D_')
    
    if caracter_separador == -1:
        continue
    
    print(caracter_separador)

    # -------------------------------------------
    print(len('_x000D_'))
    
    # -------------------------------------------
    texto1 = texto[:caracter_separador]
    print(texto1)
    texto2 = texto[caracter_separador+len('_x000D_'):]
    print(texto2)
    
    # -------------------------------------------
    if (texto1 == texto2) == True:
        texto_principal = texto1
        print(texto_principal)
    else:
        texto_principal = texto1 + ', ' + texto2
        print(texto_principal)
        
    # -------------------------------------------
    df.loc[linha, 'Diagnostico pre'] = texto_principal

In [ ]:
for linha in df.index:
    print('*'*100)
    print(linha)
    # -------------------------------------------
    texto = df.loc[linha, 'Diagnostico pre']
    print(texto)
    caracter_separador = texto.find('_x000D_')
    
    if caracter_separador == -1:
        continue
    
    print(caracter_separador)

    # -------------------------------------------
    print(len('_x000D_'))
    
    # -------------------------------------------
    texto1 = texto[:caracter_separador]
    print(texto1)
    texto2 = texto[caracter_separador+len('_x000D_'):]
    print(texto2)
    
    # -------------------------------------------
    if (texto1 == texto2) == True:
        texto_principal = texto1
        print(texto_principal)
    else:
        texto_principal = texto1 + ', ' + texto2
        print(texto_principal)
        
    # -------------------------------------------
    df.loc[linha, 'Diagnostico pre'] = texto_principal

*Retirando quebra linha da coluna 'Diagonostico Pós'*

In [ ]:
# Preenche valores nulos com uma string vazia para evitar o erro de float
df['Diagnostico pós'] = df['Diagnostico pós'].fillna('')

for linha in df.index:
    print('*'*100)
    print(linha)
    # -------------------------------------------
    texto = df.loc[linha, 'Diagnostico pós']
    print(texto)
    caracter_separador = texto.find('_x000D_')
    print(caracter_separador)

    if caracter_separador == -1:
        continue
    
    # -------------------------------------------
    print(len('_x000D_'))
    
    # -------------------------------------------
    texto1 = texto[:caracter_separador]
    print(texto1)
    texto2 = texto[caracter_separador+len('_x000D_'):]
    print(texto2)
    
    # -------------------------------------------
    if (texto1 == texto2) == True:
        texto_principal = texto1
        print(texto_principal)
    else:
        texto_principal = texto1 + ', ' + texto2
        print(texto_principal)
        
    # -------------------------------------------
    df.loc[linha, 'Diagnostico pós'] = texto_principal

*Replicando para remover quebra linha*

In [ ]:
for linha in df.index:
    print('*'*100)
    print(linha)
    # -------------------------------------------
    texto = df.loc[linha, 'Diagnostico pós']
    print(texto)
    caracter_separador = texto.find('_x000D_')
    print(caracter_separador)

    if caracter_separador == -1:
        continue
    
    # -------------------------------------------
    print(len('_x000D_'))
    
    # -------------------------------------------
    texto1 = texto[:caracter_separador]
    print(texto1)
    texto2 = texto[caracter_separador+len('_x000D_'):]
    print(texto2)
    
    # -------------------------------------------
    if (texto1 == texto2) == True:
        texto_principal = texto1
        print(texto_principal)
    else:
        texto_principal = texto1 + ', ' + texto2
        print(texto_principal)
        
    # -------------------------------------------
    df.loc[linha, 'Diagnostico pós'] = texto_principal

In [ ]:
for linha in df.index:
    print('*'*100)
    print(linha)
    # -------------------------------------------
    texto = df.loc[linha, 'Diagnostico pós']
    print(texto)
    caracter_separador = texto.find('_x000D_')
    print(caracter_separador)

    if caracter_separador == -1:
        continue
    
    # -------------------------------------------
    print(len('_x000D_'))
    
    # -------------------------------------------
    texto1 = texto[:caracter_separador]
    print(texto1)
    texto2 = texto[caracter_separador+len('_x000D_'):]
    print(texto2)
    
    # -------------------------------------------
    if (texto1 == texto2) == True:
        texto_principal = texto1
        print(texto_principal)
    else:
        texto_principal = texto1 + ', ' + texto2
        print(texto_principal)
        
    # -------------------------------------------
    df.loc[linha, 'Diagnostico pós'] = texto_principal

*Verificando score entre palavras*

In [18]:
from thefuzz import process
from thefuzz import fuzz

df['Diagnostico pós'] = df['Diagnostico pós'].fillna('')

df['score_fuzz.ratio'] = 0
df['score_fuzz.ratio'] = df['score_fuzz.ratio'].astype('float')
df['score_fuzz.token_sort_ratio'] = df['score_fuzz.ratio']
df['score_fuzz.partial_ratio'] = df['score_fuzz.ratio']

for linha in df.index:
    
    texto1 = df.loc[linha, 'Diagnostico pre']
    texto2 = df.loc[linha, 'Diagnostico pós']
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.ratio
    )
    df.loc[linha, 'score_fuzz.ratio'] = score
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.token_sort_ratio
    )
    df.loc[linha, 'score_fuzz.token_sort_ratio'] = score
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.partial_ratio
    )
    df.loc[linha, 'score_fuzz.partial_ratio'] = score
    # ===================================================
    #display(df.loc[linha:linha, ['Diagnostico pre','Diagnostico pós','score']])

In [19]:
df_bck.loc[140, 'Diagnostico pre'][2]

'G'

In [20]:
display(df_bck.loc[57:57])

display(df.loc[57:57])

,þÿNr atendimento,Nr cirurgia,Nome paciente,Ds setor atendimento,Dt inicio cirurgia,Ds procedimento,Nom usuario registro,Nome,Dt registro,Diagnostico pre,Diagnostico pós,Validacao cid
57,52868181,1889760,Cassio de Almeida Goncalves,VNS2 - Hemodinâmica,2026-03-02 18:40:00,Implante Cirúrgico De Cateter De Longa Permanê...,rafael.bmartins,Rafael Birelo Martins,2026-03-02 19:36:00,MIELOMA MULTIPLO,MIELOMA MULTIPLO,CID IGUAL

,þÿNr atendimento,Nr cirurgia,Nome paciente,Ds setor atendimento,Dt inicio cirurgia,Ds procedimento,Nom usuario registro,Nome,Dt registro,Diagnostico pre,Diagnostico pós,Validacao cid,Cor,score_fuzz.ratio,score_fuzz.token_sort_ratio,score_fuzz.partial_ratio
57,52868181,1889760,Cassio de Almeida Goncalves,VNS2 - Hemodinâmica,2026-03-02 18:40:00,Implante Cirúrgico De Cateter De Longa Permanê...,rafael.bmartins,Rafael Birelo Martins,2026-03-02 19:36:00,MIELOMA MULTIPLO,MIELOMA MULTIPLO,CID IGUAL,Verde,100.0,100.0,100.0

In [21]:
display(df[['Diagnostico pre','Diagnostico pós','score_fuzz.ratio','score_fuzz.token_sort_ratio','score_fuzz.partial_ratio']].sample(20))

,Diagnostico pre,Diagnostico pós,score_fuzz.ratio,score_fuzz.token_sort_ratio,score_fuzz.partial_ratio
167,NEOPLASIA MALIGNA DA PROSTATA,NEOPLASIA MALIGNA DA PROSTATA,100.0,100.0,100.0
438,J32 Sinusite cronica,J32 Sinusite cronica,100.0,100.0,100.0
469,M62 Outr transt musculares,M62 Outr transt musculares,100.0,100.0,100.0
789,D09.3 Tireoide e de outr gland endocrinas,D44 Neopl comp incerto/desconh gland endocrinas,62.0,61.0,68.0
257,M19 Outr artroses,M19 Outr artroses,100.0,100.0,100.0
579,D21 Outr neopl benig tec conj e outr tec moles,D21 Outr neopl benig tec conj e outr tec moles,100.0,100.0,100.0
613,J34.2 Desvio do septo nasal,J34.2 Desvio do septo nasal,100.0,100.0,100.0
226,G47.3 Apneia de sono ...,G47.3 Apneia de sono ...,100.0,100.0,100.0
679,L02.2 Abscesso cutaneo furunculo carbunculo tr...,I20 Angina pectoris,31.0,23.0,38.0
1092,HIPERTROFIA DA MAMA,HIPERTROFIA DA MAMA,100.0,100.0,100.0
999,N18 Insuf renal cronica,Z45.2 Ajustamento e manuseio disp acesso vascular,32.0,31.0,39.0
148,ESCOLIOSE,ESCOLIOSE NEUROMUSCULAR,56.0,56.0,100.0
717,C54.1 Endometrio,C54.1 Endometrio,100.0,100.0,100.0
1097,NEOPLASIA MALIGNA DA GLANDULA TIREOIDE,NEOPLASIA MALIGNA DA GLANDULA TIREOIDE,100.0,100.0,100.0
366,M95.0 Deform adquir do nariz,M95.0 Deform adquir do nariz,100.0,100.0,100.0
1005,H02.4 Ptose da palpebra,H02.4 Ptose da palpebra,100.0,100.0,100.0
1007,L05 Cisto pilonidal,L05 Cisto pilonidal,100.0,100.0,100.0
316,Endometriose,Endometriose,100.0,100.0,100.0
260,L90.5 Cicatrizes e fibrose cutanea ...,L90.5 Cicatrizes e fibrose cutanea ...,76.0,79.0,100.0
322,M19 Outr artroses,M19 Outr artroses,100.0,100.0,100.0

*Retirar linhas com score acima de 70*

In [22]:
roxo = (
        (df['score_fuzz.ratio'] < 70) &
        (df['score_fuzz.token_sort_ratio'] < 70) &
        (df['score_fuzz.partial_ratio'] < 70))

df.loc[roxo, 'Cor'] = 'Roxo'

In [23]:
df.to_excel("Discrepancia " + hospital + " 2026 (Finalizado).xlsx")