*Importando o Pandas*

In [1]:
import pandas as pd
import numpy as np

#definindo quantidade de linhas e colunas visiveis
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

*Importação de arquivos EXCEL*

In [2]:
hospital = "Santa Isabel Mar"
caminho = ('G:/Drives compartilhados/Qualidade/ACURÁCIA/DISCREPÂNCIA/DISCREPÂNCIA DIAGNÓSTICA/Discrepância 2026/Mar/')
df = pd.read_excel(caminho + 'Discrepancia ' + hospital + ' 2026.xlsx')
df_bck = df.copy()

*Criando o dataframe de CIDs.*

In [3]:
df['Cor'] = ''

*Remover linhas que não contem resposta*

In [4]:
# O raciocínio: Localize as linhas onde isnull() é True e mude a coluna 'Cor'
df.loc[df['Diagnóstico pós operatório'].isna() | df['Diagnóstico pós operatório'].str.contains(r'^\s*$', regex=True), 'Cor'] = "Amarelo"
print(df['Diagnóstico pós operatório'].isna() | df['Diagnóstico pós operatório'].str.contains(r'^\s*$', regex=True))

0       True
1      False
2      False
3       True
4      False
       ...
864    False
865    False
866     True
867    False
868     True
Name: Diagnóstico pós operatório, Length: 869, dtype: bool

*Removendo CIDs*

In [5]:
import numpy as np

# 1. Manter a limpeza de nulos inicial
df['Diagnostico pré operatório'] = df['Diagnostico pré operatório'].fillna('')

# 2. Identificação e Atribuição da Cor
padrao_cid = r"[A-Z]\d+(?:\.\d+)?"
df['Cor'] = np.where(
    df['Diagnostico pré operatório'].str.contains(padrao_cid, regex=True, na=False), 
    'Roxo', 
    ''
)

# 3. A "Lanterna" (Máscara Booleana)
# Criamos um filtro para identificar onde a Cor está vazia
mask_vazio = df['Cor'] == ''

# 4. Aplicação Cirúrgica
# Aplicamos as transformações de string APENAS nas linhas da máscara
df.loc[mask_vazio, 'Diagnostico pré operatório'] = (
    df.loc[mask_vazio, 'Diagnostico pré operatório']
    .str.replace("_x000D_", " ", regex=False)
    .str.strip()
)

print(df[['Diagnostico pré operatório', 'Cor']].head())

                          Diagnostico pré operatório Cor
0
1                             URETEROLITIASE DIREITA
2                      Varizes de membros inferiores
3
4  dor e alterações degenerativas articulares dos...

In [6]:
import numpy as np

# 1. Manter a limpeza de nulos inicial
df['Diagnóstico pós operatório'] = df['Diagnóstico pós operatório'].fillna('')

# 2. Identificação e Atribuição da Cor
padrao_cid = r"[A-Z]\d+(?:\.\d+)?"
df['Cor'] = np.where(
    df['Diagnóstico pós operatório'].str.contains(padrao_cid, regex=True, na=False), 
    'Roxo', 
    ''
)

# 3. A "Lanterna" (Máscara Booleana)
# Criamos um filtro para identificar onde a Cor está vazia
mask_vazio = df['Cor'] == ''

# 4. Aplicação Cirúrgica
# Aplicamos as transformações de string APENAS nas linhas da máscara
df.loc[mask_vazio, 'Diagnóstico pós operatório'] = (
    df.loc[mask_vazio, 'Diagnóstico pós operatório']
    .str.replace("_x000D_", " ", regex=False)
    .str.strip()
)

print(df[['Diagnóstico pós operatório', 'Cor']].head())

                          Diagnóstico pós operatório Cor
0
1                                            O MESMO
2                                            O mesmo
3
4  dor e alterações degenerativas articulares dos...

In [7]:
df.loc[df['Diagnostico pré operatório'] == df['Diagnóstico pós operatório'],'Cor'] = 'Verde'

*Classificação de Dados*

In [8]:
df.sort_values(by=["Nome paciente"])

,þÿData,Nome paciente,Atendimento,Nome do Medico,Cirurgia agendada,Cirurgia realizada,Diagnostico pré operatório,Diagnóstico pós operatório,Cid,Cor
277,2026-03-11,ALAN DUTRA SOUZA,53090132,Gabriel Santos Novaes,Ao Nível do Pé - Amputação,Ao Nível do Pé - Amputação,,,,Verde
267,2026-03-11,ANA BEATRIZ VIEIRA SILVA,53070263,Henrique Cunha Mateus,Colecistectomia Com Colangiografia Por Vídeo,Colecistectomia Com Colangiografia Por Vídeo,colelitíase,POi colecistectomia videolaparoscópica,K80,
599,2026-03-23,Abdul Mouemen Mohamad Saleh,53347013,Livio Beneduzzi Neto,Uretrotomia Interna,Uretrotomia Interna,,,N35,Verde
550,2026-03-20,Ademilson Pereira Diniz,53305228,Vania Maria Castro Baldo Rodrigues,Biópsia de Pele,Biópsia de Pele,,,,Verde
683,2026-03-25,Adilson Takayama,53421895,Gabriel Santos Novaes,Varizes - Tratamento Cirúrgico (02 Membros),Varizes - Tratamento Cirúrgico (02 Membros),,,,Verde
...,...,...,...,...,...,...,...,...,...,...
487,2026-03-18,Wilson Luiz Sanvito,53221487,Bruno Maltese Zuffo,Instalação de Cateter de Longa Permanência ( Q...,Instalação de Cateter de Longa Permanência ( Q...,FALENCIA VENOSA,FALENCIA VENOSA,I878,Verde
690,2026-03-25,Wilson Rafael Moares da Silva Serra,53423022,Joao Vitor Fernandes Lima,Bloqueio Facetário Para-espinhoso,Bloqueio Facetário Para-espinhoso,,,,Verde
2,2026-03-02,Yadni Paixao da Cunha,52867357,Nayara Marja Gil,Varizes - Tratamento Cirúrgico (02 Membros),Varizes - Tratamento Cirúrgico (02 Membros),Varizes de membros inferiores,O mesmo,I839,
471,2026-03-18,Zilma de Souza Ares,53243652,Amanda Ribas Mendes,Gastrostomia Endoscópica,Gastrostomia Endoscópica,retirada de sonda de gastrostomia,retirada de sonda de gastrostomia,,Verde
741,2026-03-27,Ítalo da Silva Lima,53406797,Rafael Figueiredo dos Santos,Cervicotomia exploradora,Cervicotomia exploradora,,,M303,Verde

*Filtrando os dados*

In [9]:
# Filtrando linhas coma palavra Convalescenca
conva = df['Diagnóstico pós operatório'].str.contains('CONVALESCENCA', na=False)
df.loc[conva, 'Cor'] = "Amarelo"
# Exibindo as linhas corretas
print(df[df['Diagnóstico pós operatório'].str.contains('CONVALESCENCA', na=False)])

Empty DataFrame
Columns: [þÿData, Nome paciente, Atendimento, Nome do Medico, Cirurgia agendada, Cirurgia realizada, Diagnostico pré operatório, Diagnóstico pós operatório, Cid, Cor]
Index: []

In [10]:
palavras = df['Diagnóstico pós operatório'].str.contains(
    '--|Mesmo|Idem|NDN|PO|POI|POS|PÓS',
    case=False,
    na=False
)

df.loc[palavras, 'Cor'] = "Amarelo"

print(df.loc[palavras, ['Diagnóstico pós operatório', 'Cor']])

                            Diagnóstico pós operatório      Cor
1                                              O MESMO  Amarelo
2                                              O mesmo  Amarelo
9                                              o mesmo  Amarelo
18                                             O MESMO  Amarelo
19                                             O mesmo  Amarelo
..                                                 ...      ...
855                     POI NEUROLISE DO NERVO MEDIANO  Amarelo
858                                            O MESMO  Amarelo
859         POI TRATAMENTO CIRURGICO DO JOELHO DIRIETO  Amarelo
860                           POI ARTROSCOPIA DE PUNHO  Amarelo
867  TRATAMENTO CIRURGICO DE FRATURA EXPOSTA DA EXT...  Amarelo

[196 rows x 2 columns]

*Verificando score entre palavras*

In [11]:
from thefuzz import process
from thefuzz import fuzz

df['Diagnóstico pós operatório'] = df['Diagnóstico pós operatório'].fillna('')

df['score_fuzz.ratio'] = 0
df['score_fuzz.ratio'] = df['score_fuzz.ratio'].astype('float')
df['score_fuzz.token_sort_ratio'] = df['score_fuzz.ratio']
df['score_fuzz.partial_ratio'] = df['score_fuzz.ratio']

for linha in df.index:
    
    texto1 = df.loc[linha, 'Diagnostico pré operatório']
    texto2 = df.loc[linha, 'Diagnóstico pós operatório']
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.ratio
    )
    df.loc[linha, 'score_fuzz.ratio'] = score
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.token_sort_ratio
    )
    df.loc[linha, 'score_fuzz.token_sort_ratio'] = score
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.partial_ratio
    )
    df.loc[linha, 'score_fuzz.partial_ratio'] = score
    # ===================================================
    #display(df.loc[linha:linha, ['Diagnostico pre','Diagnostico pós','score']])

Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

In [12]:
df_bck.loc[104, 'Diagnostico pré operatório'][2]

'l'

In [13]:
display(df_bck.loc[57:57])

display(df.loc[57:57])

,þÿData,Nome paciente,Atendimento,Nome do Medico,Cirurgia agendada,Cirurgia realizada,Diagnostico pré operatório,Diagnóstico pós operatório,Cid
57,2026-03-03,Rosilene Maria Sotero,52786420,Adriana Fernandes Silva,Passagem Sondas Por Endoscopia,Passagem Sondas Por Endoscopia,,,

,þÿData,Nome paciente,Atendimento,Nome do Medico,Cirurgia agendada,Cirurgia realizada,Diagnostico pré operatório,Diagnóstico pós operatório,Cid,Cor,score_fuzz.ratio,score_fuzz.token_sort_ratio,score_fuzz.partial_ratio
57,2026-03-03,Rosilene Maria Sotero,52786420,Adriana Fernandes Silva,Passagem Sondas Por Endoscopia,Passagem Sondas Por Endoscopia,,,,Verde,100.0,100.0,100.0

In [14]:
display(df[['Diagnostico pré operatório','Diagnóstico pós operatório','score_fuzz.ratio','score_fuzz.token_sort_ratio','score_fuzz.partial_ratio']].sample(20))

,Diagnostico pré operatório,Diagnóstico pós operatório,score_fuzz.ratio,score_fuzz.token_sort_ratio,score_fuzz.partial_ratio
447,DEISCENCIA DE FERIDA OPERATORIA,,0.0,0.0,0.0
683,,,100.0,100.0,100.0
632,,,100.0,100.0,100.0
548,Lombociatalgia,Lombociatalgia,100.0,100.0,100.0
473,hérnia epigástrica,POi hernioplastia epigástrica,72.0,73.0,88.0
342,hernia de disco extrusa l4-l5,o mesmo,22.0,22.0,43.0
215,ADENOMIOSE + CISTO SIMPLES > 6 CM EM OE,-,0.0,0.0,0.0
832,fibromialgia,fibromialgia,100.0,100.0,100.0
397,,,100.0,100.0,100.0
242,...,...,100.0,100.0,100.0
72,QUEIMADURAS SUPERFICIAIS E PROFUNDAS MEMBRO SU...,QUEIMADURAS SUPERFICIAIS E PROFUNDAS MEMBRO SU...,100.0,100.0,100.0
627,SANGRAMENTO UTERINO ANORMAL,POLIPO ENDOCERVICAL,39.0,39.0,53.0
384,,,100.0,100.0,100.0
673,HÉRNIA EPIGÁSTRICA E UMBILICAL,HÉRNIA EPIGÁSTRICA ENCARCERADA E UMBILICAL,83.0,82.0,83.0
163,,,100.0,100.0,100.0
123,trauma,trauma,100.0,100.0,100.0
598,CISTO OVARIANO SUGESTIVO DE TERATOMA À ESQUERDA,CISTO OVARIANO SUGESTIVO DE TERATOMA À ESQUERD...,66.0,66.0,100.0
437,,,100.0,100.0,100.0
739,calculo obstrutivo em ureter proximal direito,o mesmo,23.0,19.0,57.0
20,,,100.0,100.0,100.0

*Retirar linhas com score acima de 70*

In [15]:
roxo = (
        (df['score_fuzz.ratio'] > 50) &
        (df['score_fuzz.token_sort_ratio'] > 50) &
        (df['score_fuzz.partial_ratio'] > 50))

condicao_vazio = (df['Cor'].isna()) | (df['Cor'] == '')

df.loc[roxo & condicao_vazio, 'Cor'] = 'Roxo'

In [16]:
df.to_excel(caminho + 'Discrepancia ' + hospital + ' 2026 (Finalizado).xlsx')