*Importando o Pandas*

In [1]:
import pandas as pd
import numpy as np

#definindo quantidade de linhas e colunas visiveis
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

*Importação de arquivos EXCEL*

In [2]:
caminho = ('G:/Drives compartilhados/Qualidade/ACURÁCIA/DISCREPÂNCIA/DISCREPÂNCIA DIAGNÓSTICA/Discrepância 2026/Mar/')
df = pd.read_excel(caminho + 'Discrepancia Osasco Mar 2026.xlsx')
df_bck = df.copy()

In [ ]:
df['Ds setor atendimento'].value_counts()

*Criando o dataframe de CIDs.*

In [6]:
df['Cor'] = ''

In [ ]:
df.loc[df['Validacao cid'] == "CID DIFERENTE", 'Cor'] = ""

*Remover linhas que não contem resposta*

In [8]:
# O raciocínio: Localize as linhas onde isnull() é True e mude a coluna 'Cor'
df.loc[df['Diagnóstico pós operatório'].isna() | df['Diagnóstico pós operatório'].str.contains(r'^\s*$', regex=True), 'Cor'] = "Amarelo"
print(df['Diagnóstico pós operatório'].isna() | df['Diagnóstico pós operatório'].str.contains(r'^\s*$', regex=True))

0       False
1       False
2        True
3        True
4        True
        ...
1812    False
1813     True
1814    False
1815     True
1816    False
Name: Diagnóstico pós operatório, Length: 1817, dtype: bool

*Removendo CIDs*

In [10]:
import numpy as np

# 1. Manter a limpeza de nulos inicial
df['Diagnostico pré operatório'] = df['Diagnostico pré operatório'].fillna('')

# 2. Identificação e Atribuição da Cor
padrao_cid = r"[A-Z]\d+(?:\.\d+)?"
df['Cor'] = np.where(
    df['Diagnostico pré operatório'].str.contains(padrao_cid, regex=True, na=False), 
    'Roxo', 
    ''
)

# 3. A "Lanterna" (Máscara Booleana)
# Criamos um filtro para identificar onde a Cor está vazia
mask_vazio = df['Cor'] == ''

# 4. Aplicação Cirúrgica
# Aplicamos as transformações de string APENAS nas linhas da máscara
df.loc[mask_vazio, 'Diagnostico pré operatório'] = (
    df.loc[mask_vazio, 'Diagnostico pré operatório']
    .str.replace("_x000D_", " ", regex=False)
    .str.strip()
)

print(df[['Diagnostico pré operatório', 'Cor']].head())

  Diagnostico pré operatório Cor
0                        TPP
1            PARTO EXPULSIVO
2
3
4

In [13]:
import numpy as np

# 1. Manter a limpeza de nulos inicial
df['Diagnóstico pós operatório'] = df['Diagnóstico pós operatório'].fillna('')

# 2. Identificação e Atribuição da Cor
padrao_cid = r"[A-Z]\d+(?:\.\d+)?"
df['Cor'] = np.where(
    df['Diagnóstico pós operatório'].str.contains(padrao_cid, regex=True, na=False), 
    'Roxo', 
    ''
)

# 3. A "Lanterna" (Máscara Booleana)
# Criamos um filtro para identificar onde a Cor está vazia
mask_vazio = df['Cor'] == ''

# 4. Aplicação Cirúrgica
# Aplicamos as transformações de string APENAS nas linhas da máscara
df.loc[mask_vazio, 'Diagnóstico pós operatório'] = (
    df.loc[mask_vazio, 'Diagnóstico pós operatório']
    .str.replace("_x000D_", " ", regex=False)
    .str.strip()
)

print(df[['Diagnóstico pós operatório', 'Cor']].head())

  Diagnóstico pós operatório Cor
0                        TPP
1                    O MESMO
2
3
4

In [14]:
df.loc[df['Diagnostico pré operatório'] == df['Diagnóstico pós operatório'],'Cor'] = 'Verde'

*Classificação de Dados*

In [ ]:
df.sort_values(by=["Nome paciente"])

In [ ]:
contagem = df['Ds setor atendimento'].value_counts()
print(contagem)

*Filtrando os dados*

In [15]:
# Filtrando linhas coma palavra Convalescenca
conva = df['Diagnóstico pós operatório'].str.contains('CONVALESCENCA', na=False)
df.loc[conva, 'Cor'] = "Amarelo"
# Exibindo as linhas corretas
print(df[df['Diagnóstico pós operatório'].str.contains('CONVALESCENCA', na=False)])

Empty DataFrame
Columns: [þÿData, Nome paciente, Atendimento, Nome do Medico, Cirurgia agendada, Cirurgia realizada, Diagnostico pré operatório, Diagnóstico pós operatório, Cid, Cor]
Index: []

In [16]:
outros = df['Diagnóstico pós operatório'].str.contains('OUTROS', na=False)
df.loc[outros, 'Cor'] = " Amarelo"

print(df[df['Diagnóstico pós operatório'].str.contains('OUTROS', na=False)])

Empty DataFrame
Columns: [þÿData, Nome paciente, Atendimento, Nome do Medico, Cirurgia agendada, Cirurgia realizada, Diagnostico pré operatório, Diagnóstico pós operatório, Cid, Cor]
Index: []

In [17]:
segui = df['Diagnóstico pós operatório'].str.contains('Seguimentos', na=False)
df.loc[segui, 'Cor'] = " Amarelo"

print(df[df['Diagnóstico pós operatório'].str.contains('Seguimentos', na=False)])

Empty DataFrame
Columns: [þÿData, Nome paciente, Atendimento, Nome do Medico, Cirurgia agendada, Cirurgia realizada, Diagnostico pré operatório, Diagnóstico pós operatório, Cid, Cor]
Index: []

In [24]:
palavras = df['Diagnóstico pós operatório'].str.contains(
    'Mesmo|Idem|NDN|PO|POI|POS|PÓS',
    na=False
)

df.loc[palavras, 'Cor'] = "Amarelo"

print(df.loc[palavras, ['Diagnóstico pós operatório', 'Cor']])

                             Diagnóstico pós operatório      Cor
16                                     POI DE CESARIANA  Amarelo
18                                  POI DE PARTO NORMAL  Amarelo
52     # PO (02/03/26) POSTECTOMIA- Sem intercorrências  Amarelo
117                                 POI DE PARTO NORMAL  Amarelo
131                                    POI DE CESARIANA  Amarelo
173   POI RESSECÇÃO SEGMENTAR MAMA ESQUERDA + RECONS...  Amarelo
239   ELAGASTROPARESIADIFICULADADE DE DGLUTIÇÃOHIPER...  Amarelo
266                                    POI DE CESARIANA  Amarelo
270   TROMBOSE HEMORROIDWERIAABSCESSO ANAL INTERESFI...  Amarelo
278   ABSCESSO ISQUIORRETAL EM FERRADURAFISTULA EM F...  Amarelo
288   TROMBOSE HEMORROIDARIAPROLAPSO MUCOSO EDEMACIA...  Amarelo
299   ABSCESSO ISQUIORRETAL E INTERESFINCTERIANOFIST...  Amarelo
331   POI OSTEOSSINTESE DE 5 MTC + REPARO LIGAMENTAR...  Amarelo
358                                                 NDN  Amarelo
362                                         POI DE AMIU  Amarelo
368   M532 Instabilidades da coluna vertebral.ESPOND...  Amarelo
371                                  POI D EPOSTECTOMIA  Amarelo
423   POI LIBERAÇÃO ENDOSCÓPICA DO TÚNEL DO CARPO + ...  Amarelo
430   POI RESSECÇÃO DE CISTO SINOVIAL DE PUNHO DIREI...  Amarelo
511              PÓS OP DE CORREÇÃO DE LESÃO LIGAMENTAR  Amarelo
561   - ABSCESSO  ANAL INTERESFINCTERIANAO ANTERIOR ...  Amarelo
584                                    POI DE CESARIANA  Amarelo
591                     POI EXTENSOS FERIMENTOS DE 2QDD  Amarelo
593                                       POI CESARIANA  Amarelo
596                                       POI CESARIANA  Amarelo
600                                 POI DE PARTO NORMAL  Amarelo
610            POI DE RESSECÇÃO DE DEDO EXTRA NUMERÁRIO  Amarelo
623                      POI DE HERNIORRAFIA  UMBILICAL  Amarelo
654             POI EXÉRESE DE MAMA ACESSÓRIA BILATERAL  Amarelo
674                                 POI DE PARTO NORMAL  Amarelo
738                         TROCA DE CÂNULA POR UMA N 6  Amarelo
740                                 POI DE PARTO NORMAL  Amarelo
828                                    POI DE CESARIANA  Amarelo
873   POI RESSECÇÃO DE CISTO SINOVIAL DE PUNHO ESQUERDO  Amarelo
880   POI ressecção de cisto de bainha de tendão de ...  Amarelo
947   PROCIDENCIA ANORRETAL GRAU III- HEMORRÓIDAS GR...  Amarelo
956   - HEMORROIDA GRAU IV COM PLICOMA- FISSURA ANAL...  Amarelo
1055  PROCIENCIA RETAL VOLUMOSA EDEMACIADATROMBOSE H...  Amarelo
1127                                POI DE PARTO NORMAL  Amarelo
1130  LIBERAÇÃO ABERTA DO TUNEL DO CARPO DIREITO + I...  Amarelo
1132  POI BLOQUEIO NERVOS GENICULARES E VISCOSSUPLEM...  Amarelo
1144        POI BLOQUEIO SACROILIACAS E QUADRIL DIREITO  Amarelo
1150                       POI BLOQUEIO COLUNA CERVICAL  Amarelo
1153  POI RETIRADA DE MATERIAL DE SINTESE DE PUNHOS ...  Amarelo
1160  POI RECONSTRUCAO LCA E REGULARIZACAO MENISCAL ...  Amarelo
1174  POI OSTEOSSINTESE DE RADIO E ULNA DIAFISARIOS ...  Amarelo
1185                                   POI DE CESARIANA  Amarelo
1209                                   POI DE CESARIANA  Amarelo
1222                             POI DE CTG  PÓS-ABORTO  Amarelo
1312                                POI DE PARTO NORMAL  Amarelo
1314                                           POT CPRE  Amarelo
1367  - ABSCESSO  ANAL INTERESFINCTERIANAO ANTERIOR ...  Amarelo
1442  - - HEMORROIDA GRAU IV COM TROMBOSE AS 8 HORAS...  Amarelo
1464         HEMATOMA EM LOJA APOS AGITAÇÃO PSICOMOTORA  Amarelo
1497  HEMORROIDAFISSURA ANAL POLIPO RETALPROLAPSO MU...  Amarelo
1513  TROMBOSE HEMORROIDARIA GRANDEPROLAPOSO MUCOSO ...  Amarelo
1564  POS OP DE OSTEOSSINTESE DE FALANGE PROXIMAL DE...  Amarelo
1566                                POI DE PARTO NORMAL  Amarelo
1575                                POI DE PARTO NORMAL  Amarelo
1582                                POI DE PARTO NORMAL  Amarelo
1695  PO REPARO LIGAMENTAR DO COLATERAL ULNAR DO POL...  Amarelo
1781                                POI DE PARTO NORMAL  Amarelo
1788                                           POI AMIU  Amarelo

*Verificando score entre palavras*

In [18]:
from thefuzz import process
from thefuzz import fuzz

df['Diagnóstico pós operatório'] = df['Diagnóstico pós operatório'].fillna('')

df['score_fuzz.ratio'] = 0
df['score_fuzz.ratio'] = df['score_fuzz.ratio'].astype('float')
df['score_fuzz.token_sort_ratio'] = df['score_fuzz.ratio']
df['score_fuzz.partial_ratio'] = df['score_fuzz.ratio']

for linha in df.index:
    
    texto1 = df.loc[linha, 'Diagnostico pré operatório']
    texto2 = df.loc[linha, 'Diagnóstico pós operatório']
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.ratio
    )
    df.loc[linha, 'score_fuzz.ratio'] = score
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.token_sort_ratio
    )
    df.loc[linha, 'score_fuzz.token_sort_ratio'] = score
    # ===================================================
    melhor, score = process.extractOne(
        query=texto1,
        choices=[texto2],
        scorer=fuzz.partial_ratio
    )
    df.loc[linha, 'score_fuzz.partial_ratio'] = score
    # ===================================================
    #display(df.loc[linha:linha, ['Diagnostico pre','Diagnostico pós','score']])

Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

In [19]:
df_bck.loc[140, 'Diagnostico pré operatório'][2]

'D'

In [20]:
display(df_bck.loc[57:57])

display(df.loc[57:57])

,þÿData,Nome paciente,Atendimento,Nome do Medico,Cirurgia agendada,Cirurgia realizada,Diagnostico pré operatório,Diagnóstico pós operatório,Cid
57,2026-03-02,Joao Gomes de Almeida Filho,52819237,Rodrigo Mendonça Dionisio,Cateterismo de Câmaras Cardíacas Esquerdas E C...,Cateterismo de Câmaras Cardíacas Esquerdas E C...,,,

,þÿData,Nome paciente,Atendimento,Nome do Medico,Cirurgia agendada,Cirurgia realizada,Diagnostico pré operatório,Diagnóstico pós operatório,Cid,Cor,score_fuzz.ratio,score_fuzz.token_sort_ratio,score_fuzz.partial_ratio
57,2026-03-02,Joao Gomes de Almeida Filho,52819237,Rodrigo Mendonça Dionisio,Cateterismo de Câmaras Cardíacas Esquerdas E C...,Cateterismo de Câmaras Cardíacas Esquerdas E C...,,,,Verde,100.0,100.0,100.0

In [21]:
display(df[['Diagnostico pré operatório','Diagnóstico pós operatório','score_fuzz.ratio','score_fuzz.token_sort_ratio','score_fuzz.partial_ratio']].sample(20))

,Diagnostico pré operatório,Diagnóstico pós operatório,score_fuzz.ratio,score_fuzz.token_sort_ratio,score_fuzz.partial_ratio
768,,,100.0,100.0,100.0
1093,fistula dural,fistula dural pos trombose venosa cerebral,47.0,47.0,100.0
368,M532 Instabilidades da coluna vertebral.ESPOND...,M532 Instabilidades da coluna vertebral.ESPOND...,100.0,100.0,100.0
322,Prolapso de reto encarcerado com sangramento a...,Prolapso de reto encarcerado com sangramento a...,100.0,100.0,100.0
91,desvio septal,desvio septal,100.0,100.0,100.0
225,,,100.0,100.0,100.0
1485,VARIZES,TCVB,18.0,18.0,40.0
1393,TRABALHO DE PARTO,O MESMO,33.0,33.0,43.0
1657,,,100.0,100.0,100.0
926,OBESIDADE MÓRBIDA,O MESMO,33.0,26.0,55.0
405,,,100.0,100.0,100.0
1217,,,100.0,100.0,100.0
84,N200,N200,100.0,100.0,100.0
1418,APENDICITE AGUDA,APENDICITE AGUDA + COLEÇÃO /ABCESSO PÉLVICO + ...,29.0,32.0,100.0
1285,ABORTO INCOMPLETO,O MESMO,42.0,25.0,57.0
1793,,,100.0,100.0,100.0
1260,,,100.0,100.0,100.0
620,,,100.0,100.0,100.0
1153,EXTENSOS FERIMENTOS DE PUNHO BILATERAL,POI RETIRADA DE MATERIAL DE SINTESE DE PUNHOS ...,65.0,56.0,75.0
1613,,,100.0,100.0,100.0

*Retirar linhas com score acima de 70*

In [22]:
roxo = (
        (df['score_fuzz.ratio'] > 50) &
        (df['score_fuzz.token_sort_ratio'] > 50) &
        (df['score_fuzz.partial_ratio'] > 50))

condicao_vazio = (df['Cor'].isna()) | (df['Cor'] == '')

df.loc[roxo & condicao_vazio, 'Cor'] = 'Roxo'

In [23]:
df.to_excel("Discrepancia Osasco Mar 2026(teste1).xlsx")